---
- hosts: all
  become: yes


  tasks:

  - name: Install kubernetes
    apt: 
      pkg:
        - kubelet=1.19.1-00
        - kubeadm=1.19.1-00
        - kubectl=1.19.1-00
      update_cache: yes


  - name: Initialize Kubelet
    command: kubeadm init --pod-network-cidr=192.168.0.0/16 --kubernetes-version 1.19.1 --apiserver-advertise-address 10.5.2.120
    run_once: true

  - name: Enable kubelet
    service:
      name: kubelet
      enabled: yes

  - name: Create kube-config
    file:
      path: /home/vagrant/.kube
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0755

  - name: Copy admin.conf to .kube/config
    become_user: root
    become_method: sudo 
    become:  yes
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      remote_src: yes
      owner: vagrant
      group: vagrant
      mode: '0644'

  - name: Disable IP tables
    shell: |
      echo "net.bridge.bridge-nf-call-iptables=1" >> /etc/sysctl.conf
      echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
      sysctl -p

  - name: Download cni
    get_url:
      url: https://docs.projectcalico.org/v3.15/manifests/calico.yaml
      dest: /home/vagrant/calico.yaml

  - name: Deploy pod network
    command: kubectl apply -f /home/vagrant/calico.yaml
    run_once: yes

