---
- hosts: all
  become: yes


  tasks:

  - name: Copy etc-hosts file
    copy:
      src: hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Put SELinux in permissive mode
    ansible.posix.selinux:
      policy: targeted
      state: permissive

  - name: Configure iptables to see bridged traffic
    shell: |
      echo "net.bridge.bridge-nf-call-iptables=1" >> /etc/sysctl.conf
      echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
      sysctl -p

  - name: Configure firewall - 6443
    ansible.posix.firewalld:
      port: 6443/tcp
      permanent: yes
      state: enabled

  - name: Configure firewall - 2379-2380
    ansible.posix.firewalld:
      port: 2379-2380/tcp
      permanent: yes
      state: enabled

  - name: Configure firewall - 10250-10252
    ansible.posix.firewalld:
      port: 10250-10252/tcp
      permanent: yes
      state: enabled

