---
- hosts: all
  become: yes

  tasks:

  - name: Upgrade all packages
    dnf:
      name: "*"
      state: latest

  - name: Copy etc-hosts file
    copy:
      src: hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Put SELinux in permissive mode
    ansible.posix.selinux:
      policy: targeted
      state: permissive

  - name: Modprobe br_netfilter
    modprobe: 
      name: br_netfilter
      state: present

  - name: Set bridge iptables in sysctl
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present
      reload: yes

  - name: Set ip_forward
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present
      reload: yes

  - name: Configure firewall - 6443
    ansible.posix.firewalld:
      port: 6443/tcp
      permanent: yes
      state: enabled

  - name: Configure firewall - 2379-2380
    ansible.posix.firewalld:
      port: 2379-2380/tcp
      permanent: yes
      state: enabled      

  - name: Configure firewall - 10250-10252
    ansible.posix.firewalld:
      port: 10250-10252/tcp
      permanent: yes
      state: enabled

  - name: Enable firewall
    systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: Enable EPEL
    dnf: 
      name: epel-release
      state: latest

  - name: Install tools
    dnf:
      name: 
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - vim

  - name: download docker installer
    get_url:
      url: https://get.docker.com/
      dest: /root/install_docker.sh
      mode: 0700
  
  - name: Install Docker
    shell: /root/install_docker.sh

  - name: Remove the Docker installer file.
    file:
      state: absent
      path: /root/install_docker.sh

  - name: Create etc-docker directory
    file: 
      path: /etc/docker/
      state: directory

  - name: Copy docker daemon setup
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'

  - name: Enable the Docker daemon in systemd
    systemd:
      name: docker
      enabled: yes
      state: started
      masked: no

  - name: Add vagrant user to docker
    user:
      name: vagrant
      groups: docker,wheel
      append: yes