---
- hosts: all

  tasks:
  
  - name: Setup K8s repo
    become: yes
    copy:
      src: kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo
      owner: root
      group: root
      mode: 0644

  - name: Install k8s
    become: yes
    dnf:
      name: 
        - kubelet
        - kubeadm
        - kubectl
      disable_excludes: all
  
  - name: Enable Kubelet in systemd
    become: yes
    systemd:
      name: kubelet
      enabled: yes
      state: started
      masked: no

  - name: Initialize Kubelet
    become: yes
    shell: kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address 10.5.5.120

  - name: set permissions for admin.com
    become: yes
    file:
      path: /etc/kubernetes/admin.conf
      mode: 0644

  - name: Create kube-config
    become: yes
    become_user: vagrant
    file:
      path: $HOME/.kube
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0755

  - name: Copy admin.conf to .kube/config
    become: yes
    become_user: vagrant
    copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes
      owner: vagrant
      group: vagrant
      mode: '0644'

  - name: Install CNI
    become: yes
    become_user: vagrant
    command: kubectl apply -f /vagrant/calico.yaml
    
  - name: Create join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to vagrant dir
    become: false
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"