---
- hosts: all
  become: yes

  tasks:

  - name: Upgrade all packages
    dnf:
      name: "*"
      state: latest

  - name: Copy etc-hosts file
    copy:
      src: hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Put SELinux in permissive mode
    ansible.posix.selinux:
      policy: targeted
      state: permissive

  - name: Modprobe br_netfilter
    modprobe: 
      name: br_netfilter
      state: present

  - name: Set bridge iptables in sysctl
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present
      reload: yes

  - name: Set ip_forward
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present
      reload: yes

  - name: Configure firewall - 10250
    ansible.posix.firewalld:
      port: 10250/tcp
      permanent: yes
      state: enabled

  - name: Configure firewall - 30000-32767
    ansible.posix.firewalld:
      port: 30000-32676/tcp
      permanent: yes
      state: enabled

  - name: Enable firewall
    systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: Enable EPEL
    dnf: 
      name: epel-release
      state: latest

  - name: Install pre-flight packages
    dnf:
      name: 
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - vim
      state: present

  - name: Add vagrant user to wheel
    user:
      name: vagrant
      groups: wheel
      append: yes