---
- hosts: all

  tasks:

  - name: Copy the join command to server location
    become: yes
    copy: 
      src: join-command
      dest: /tmp/join-command.sh 
      mode: 0755

  - name: Join the node to cluster
    become: yes
    command: sh /tmp/join-command.sh