
IMAGE_NAME = "centos/8"
NETWORK = "10.5.5.12"
MEMORY = "4096"
CPUS = "2"
N = 3


Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_NAME
  config.vm.disk :disk, size: "40GB", primary: true
  config.vm.provider "virtualbox" do |v|
    v.memory = "#{MEMORY}"
    v.cpus = "#{CPUS}"
  end

  config.vm.define "master" do |master|
    master.vm.hostname = "c1-master1"
    master.vm.network "private_network", ip: "#{NETWORK}0"
    master.vm.provision :ansible do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "pre-flight.yaml"
    end
    master.vm.provision :ansible do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "master-firewall-config.yaml"
    end
    master.vm.provision :ansible do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "install-configure-cri.yaml"
    end
    master.vm.provision :ansible do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "install-k8s.yaml"
    end
    master.vm.provision :ansible do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "master-config-k8s.yaml"
    end
  end

  (1..N).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "c1-node#{i}"
      node.vm.network "private_network", ip: "#{NETWORK}#{i}"
      node.vm.provision :ansible do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "pre-flight.yaml"
      end
      node.vm.provision :ansible do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "node-firewall-config.yaml"
      end
      node.vm.provision :ansible do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "install-configure-cri.yaml"
      end
      node.vm.provision :ansible do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "install-k8s.yaml"
      end
      node.vm.provision :ansible do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "node-config-k8s.yaml"
      end
    end
  end
end
